name       : python-dogpile-cache
version    : 1.1.4
release    : 6
source     :
    - https://pypi.io/packages/source/d/dogpile.cache/dogpile.cache-1.1.4.tar.gz : ea09bebf24bb7c028caf98963785fe9ad0bd397305849a3303bc5380d468d813
license    : BSD-3-Clause
component  : programming.python
summary    : A caching front-end based on the Dogpile lock.
description: |
    A caching front-end based on the Dogpile lock.
builddeps  :
    - mako
    - python-decorator
    - python-markupsafe
    - python-mock # check
    - python-pytest-cov # check
    - python-stevedore
rundeps    :
    - python-decorator
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    needs newer pytest
#    %python3_test py.test3
