name       : python-dogpile-cache
version    : 0.6.7
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/d/dogpile.cache/dogpile.cache-0.6.7.tar.gz : fca7deb7c276b879b01c15c5d39b3c05701dc43b263ec3fef1e52cb851cf88ab
license    : BSD-3-Clause
component  : programming.python
summary    : A caching front-end based on the Dogpile lock.
description: |
    A caching front-end based on the Dogpile lock.
builddeps  :
    - mako
    - python-markupsafe
    - python-mock
    - python-pytest-cov
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
