name       : python-dogpile-cache
version    : 1.1.8
release    : 9
source     :
    - https://pypi.io/packages/source/d/dogpile.cache/dogpile.cache-1.1.8.tar.gz : d844e8bb638cc4f544a4c89a834dfd36fe935400b71a16cbd744ebdfb720fd4e
homepage   : https://github.com/sqlalchemy/dogpile.cache
license    : BSD-3-Clause
component  : programming.python
summary    : A caching front-end based on the Dogpile lock
description: |
    dogpile.cache is a Python caching API which provides a generic interface to caching backends of any variety.
builddeps  :
    - mako
    - python-decorator
    - python-mock       # check
    - python-pytest-cov # check
    - python-stevedore
rundeps    :
    - python-decorator
    - python-stevedore
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
