name       : python-dogpile-cache
version    : 1.1.5
release    : 7
source     :
    - https://pypi.io/packages/source/d/dogpile.cache/dogpile.cache-1.1.5.tar.gz : 0f01bdc329329a8289af9705ff40fadb1f82a28c336f3174e12142b70d31c756
homepage   : https://github.com/sqlalchemy/dogpile.cache
license    : BSD-3-Clause
component  : programming.python
summary    : A caching front-end based on the Dogpile lock
description: |
    dogpile.cache is a Python caching API which provides a generic interface to caching backends of any variety.
builddeps  :
    - mako
    - python-decorator
    - python-mock # check
    - python-pytest-cov # check
    - python-stevedore
rundeps    :
    - python-decorator
    - python-stevedore
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
