name       : python-dogpile-cache
version    : 0.8.0
release    : 5
source     :
    - https://files.pythonhosted.org/packages/29/e2/f850b80eac4937c6d9ea6a24fac3764d951d82eb5f3e9a8ccd6ac24d70f8/dogpile.cache-0.8.0.tar.gz : 70f5eae4aec908f76188a2c287e07105f60c05d879bb9a4efcc5ba44563d8de6
license    : BSD-3-Clause
component  : programming.python
summary    : A caching front-end based on the Dogpile lock.
description: |
    A caching front-end based on the Dogpile lock.
builddeps  :
    - mako
    - python-decorator
    - python-markupsafe
    - python-mock
    - python-pytest-cov
rundeps    :
    - python-decorator
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
