name       : python-dogpile-cache
version    : 0.6.2
release    : 1
source     :
    - https://pypi.python.org/packages/9d/a9/ba70aadc6170841a1c6145e9039d4b1c2a4ef8c44cd0ca9b09ab79be9120/dogpile.cache-0.6.2.tar.gz : 73793471af07af6dc5b3ee015abfaca4220caaa34c615537f5ab007ed150726d
license    : BSD-3-Clause
component  : programming.python
summary    : A caching front-end based on the Dogpile lock.
description: |
    A caching front-end based on the Dogpile lock.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
